site_name: LabIFSC2
nav:
  - Sobre: index.md
  - Introdução: introducao.md
  - Constantes: constantes da natureza.md
  - Funções Matemáticas: funcoes_matematicas.md
  - Arrays: arrays.md
  - Mínimos quadrados: regressoes_menu.md
  - Gráficos: graficos.md
  - Formataçõs/LaTeX: formatacoes_latex.md
  - Como erros são propagados?: propagacao_de_erros.md
  - API Completa: api.md
  - Como contribuir: contribuir.md

repo_url: https://github.com/viniciusdutra314/LabIFSC2
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

use_directory_urls: false
plugins:
  - search
  - mkdocstrings
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - pymdownx.highlight:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math
  - footnotes