[tool.poetry]
name = "labifsc2"
version = "0.1.0"
description = ""
authors = ["viniciusdutra314 <dutravinisousa2@usp.br>"]
license = "GNU General Public License v3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
numpy = "2.*"
pint = "^0.24"

[tool.taskipy.tasks]
lint = "isort ."
pre_testes = "task lint"
testes="pytest --tb=no"
docs="mkdocs serve"

[tool.isort]
profile = "black"
line_length = 79
multi_line_output=0

[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.4"
pymdown-extensions = "^10.7"
python-markdown-math = "^0.8"
mkdocstrings = "^0.27.0"
mkdocstrings-python = "^1.13.0"


[tool.poetry.group.test.dependencies]
labifsc = "^0.1.13"
uncertainties = "^3.2.2"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"


[tool.poetry.group.linter.dependencies]
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
