[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "LabIFSC2"
version = "0.1.1"
description = "Cálculos de laboratório com Python, realize propagação de incertezas e conversão de medidas automaticamente"
authors = ["viniciusdutra314 <dutravinisousa2@usp.br>"]
license = "GNU General Public License v3.0"
readme = "README.md"
packages=[{include = "LabIFSC2"}]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: Portuguese (Brazilian)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
]
keywords=["LabIFSC","montecarlo","error_propagation","unit_conversion"]

[tool.poetry.urls]
"Documentation" = "https://labifsc2.readthedocs.io/pt-br/latest/"
"Github" = "https://github.com/viniciusdutra314/LabIFSC2"
"Issue Tracker"="https://github.com/viniciusdutra314/LabIFSC2/issues"

[tool.poetry.dependencies]
python = ">=3.10 , <3.13"
numpy = ">= 1.26"
pint = "^0.24"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.4"
pymdown-extensions = "^10.7"
python-markdown-math = "^0.8"
mkdocstrings = "^0.27.0"
mkdocstrings-python = "^1.13.0"


[tool.poetry.group.test.dependencies]
labifsc = "^0.1.13"
uncertainties = "^3.2.2"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
scipy = "^1.15.1"


[tool.poetry.group.linter.dependencies]
taskipy = "^1.14.1"
isort = "^5.13.2"
mypy = "1.14.1"


[tool.poetry.group.testes.dependencies]
matplotlib = "^3.10.0"

[tool.mypy]
strict = false
disallow_any_generics = false
exclude = 'tests/.*'

[tool.taskipy.tasks]
testes={ cmd="isort . && mypy LabIFSC2/ --exclude LabIFSC2/_tipagem_forte.py && pytest -vv -x -s --cov LabIFSC2/ --cov-append  --no-cov-on-fail --cov-branch --cov-report=html "}
docs="mkdocs serve"

