[tool.poetry]
name = "labifsc2"
version = "0.1.0"
description = ""
authors = ["viniciusdutra314 <dutravinisousa2@usp.br>"]
license = "GNU General Public License v3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
numpy = "2.*"
pint = "^0.24"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.4"
pymdown-extensions = "^10.7"
python-markdown-math = "^0.8"
mkdocstrings = "^0.27.0"
mkdocstrings-python = "^1.13.0"


[tool.poetry.group.test.dependencies]
labifsc = "^0.1.13"
uncertainties = "^3.2.2"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
scipy = "^1.15.1"


[tool.poetry.group.linter.dependencies]
taskipy = "^1.14.1"
isort = "^5.13.2"
mypy = "1.14.1"


[tool.poetry.group.testes.dependencies]
matplotlib = "^3.10.0"

[tool.mypy]
strict = true
disallow_any_generics = false
exclude = 'tests/.*'

[tool.taskipy.tasks]
testes={ cmd="isort . && mypy LabIFSC2/ && pytest -vv -x -s --cov LabIFSC2/ --no-cov-on-fail --cov-branch --cov-report=html "}
docs="mkdocs serve"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
